version: '3'
services:
    nginx:
        image: nginx
        container_name: LEMP_nginx
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./mysite/:/var/www/html/
        depends_on:
            - php

    php:
        image: php:7-fpm
        container_name: LEMP_php
        ports:
            - "9000:9000"
        volumes:
            - ./mysite/:/var/www/html/

    mariaDB:
        image: mariadb
        container_name: LEMP_mariadb
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=dbname
        depends_on:
            - nginx

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpmyadmin
        ports:
            - "81:80"
        environment:
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB