version: '3'
services:
    nginx:
        image: nginx
        container_name: LEMP_nginx
        ports:
            - "80:80"
        volumes:
            - ./default:/etc/nginx/sites-enabled/default
            - ./index.php:/var/www/html/index.php
        depends_on:
            - php

    php:
        image: php:7-fpm
        container_name: LEMP_php
        ports:
            - "9000:9000"

    mariaDB:
        image: mariadb
        container_name: LEMP_mariaDB
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        depends_on:
            - nginx

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpmyadmin
        ports:
            - "81:80"
        environment:
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB